branches:
  only:
  - blog
language: node_js
node_js:
- '0.10'
install:
- npm install hexo@beta -g
- npm install
script:
- hexo d -g
before_install:
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in travis.enc -out travis -d
