branches:
  only:
  - blog

language: node_js

node_js:
- '0.10'

before_install:
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in doc/travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp doc/ssh_config ~/.ssh/config
- git config --global user.name "xuanwo"
- git config --global user.email xuanwo.cn@gmail.com

install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install hexo-deployer-git --save
- npm install hexo-generator-archive --save
- npm install hexo-generator-category --save
- npm install hexo-generator-feed --save
- npm install hexo-generator-index --save
- npm install hexo-generator-sitemap --save
- npm install hexo-generator-tag --save
- npm install hexo-renderer-ejs --save
- npm install hexo-renderer-marked --save
- npm install hexo-renderer-stylus --save

script:
- hexo clean
- hexo g
- mv public git
- cd git
- git init
- git add -A
- git commit -m "Update"
- git push git@github.com:Xuanwo/xuanwo.github.io.git master:master --force
- git push git@gitcafe.com:xuanwo/xuanwo.git master:gitcafe-pages --force


addons:
  ssh_known_hosts:
  - github.com
  - gitcafe.com
