branches:
  only:
  - blog

language: node_js

node_js:
- '0.10'

before_install:
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in doc/travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp doc/ssh_config ~/.ssh/config
- git config --global user.name "xuanwo"
- git config --global user.email xuanwo.cn@gmail.com
- mkdir .deploy_git
- git clone -b master git@github.com:Xuanwo/xuanwo.github.io.git .deploy_git

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- nom install hexo-deployer-git --save

script:
- hexo clean
- hexo g
- hexo d
