branches:
  only:
  - blog

language: node_js

node_js:
- '0.10'

before_install:
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in doc/travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp doc/ssh_config ~/.ssh/config
- git config --global user.name "Xuanwo"
- git config --global user.email vars.cn@gmail.com

install:
- npm install hexo-cli -g
- npm install hexo@beta --save
- npm install hexo-deployer-git --save
- npm install hexo-generator-archive
- npm install hexo-generator-category
- npm install hexo-generator-feed
- npm install hexo-generator-index
- npm install hexo-generator-sitemap
- npm install hexo-generator-tag
- npm install hexo-renderer-ejs
- npm install hexo-renderer-marked
- npm install hexo-renderer-stylus
- npm install hexo-server

script:
- hexo clean
- hexo g
- hexo d