title: Xuanwo's Blog
email: xuanwo.cn@gmail.com
description: >
    Long way to go
baseurl: "" 
url: "https://xuanwo.org"
twitter_username: onlyxuanwo
github_username:  Xuanwo

permalink: /:year/:month/:day/:title/
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: only0god

google_analytics: UA-51515330-1

kramdown:
  input: GFM
