slogan: Keep Going

menu:
  - title: Archives
    url: archives
    intro: All the articles.
    icon: fa fa-archive
  - title: Categories
    url: categories
    intro: All the categories.
    icon: fa fa-folder
  - title: Tags
    url: tags
    intro: All the tags.
    icon: fa fa-tags
  - title: Works
    url: works
    intro: My own works
    icon: fa fa-book
  - title: To do
    url: todo
    intro: All the thing I want to do.
    icon: fa fa-check-square-o
  - title: About
    url: about
    intro: About me.
    icon: fa fa-user

links:
  - title: My Github
    url: https://www.github.com/xuanwo
    intro: My Github account.
    icon: fa fa-github
  - title: 小媛在努力
    url: http://www.xysay.com/
    intro: 自从大一下接触ACM，踏上了一条不归路，有了这个CSDN水题解博客
    icon: fa fa-user
  - title: 周良博客
    url: http://www.aips.me/
    intro: 关注 WordPress 与互联网的原创IT科技博客
    icon: fa fa-user

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: atom.xml
fancybox: true
favicon: favicon.ico
google_analytics: UA-51515330-1