slogan: Keep Going

menu:
  - title: Archives
    url: archives
    intro: All the articles.
    icon: fa fa-archive
  - title: Categories
    url: categories
    intro: All the categories.
    icon: fa fa-folder
  - title: Tags
    url: tags
    intro: All the tags.
    icon: fa fa-tags
  - title: About
    url: about
    intro: About me.
    icon: fa fa-user

links:
  - title: My Github
    url: https://www.github.com/xuanwo
    intro: My Github account.
    icon: fa fa-github
  - title: FreeMeepo
    url: http://www.freemeepo.com/acm/
    intro: FreeMeepo's Blog
    icon: fa fa-user
  - title: Walk Upon
    url: http://blog.csdn.net/walk_upon
    intro: Walk Upon's Blog
    icon: fa fa-user

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: atom.xml
fancybox: true
favicon: favicon.ico
google_analytics: UA-51515330-1