# Header
menu:
  Archives: /archives
  Opinion: /categories/Opinion/
  Category: /categories
  Tags: /tags
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-51515330-1
favicon: /favicon.ico