# Header
menu:
  Home: /
  Archives: /archives
  About: /about/index.html
rss: atom.xml
github: https://github.com/Xuanwo

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- archive
- recent_posts
- tag
- links

# Links
links: 
  Hexo: http://hexo.io

# Miscellaneous
google_analytics: UA-51515330-1
favicon: /favicon.png